# Generated by Django 5.1.6 on 2025-09-02 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('display_email', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopArtistsListened',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(blank=True, max_length=20, null=True)),
                ('artist_image', models.URLField(blank=True, null=True)),
                ('total_played', models.PositiveIntegerField(default=0)),
                ('listened_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_artist', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MusicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_type', models.CharField(blank=True, max_length=20, null=True)),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music_type', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('day', models.DateField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listening_activity', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserRecentPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_image', models.URLField(blank=True, null=True)),
                ('track_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('track_owner', models.CharField(blank=True, max_length=1000, null=True)),
                ('track_duration', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recent_played', to='users.userprofile')),
            ],
        ),
    ]
