# Generated by Django 5.1.6 on 2025-09-03 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_country_userprofile_followers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyListened',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(blank=True, max_length=20, null=True)),
                ('track_name', models.CharField(blank=True, max_length=20, null=True)),
                ('artist_image', models.URLField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recent_listen', to='users.userprofile')),
            ],
        ),
    ]
