# Generated by Django 5.1.6 on 2025-09-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_recentlylistened'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentlyListened',
        ),
    ]
