# Generated by Django 5.1.6 on 2025-09-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_recentlylistened'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecentplayed',
            name='played_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
