# Generated by Django 5.1.6 on 2025-09-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userrecentplayed_played_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecentplayed',
            name='track_id',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
